# -*- coding: utf-8 -*-
"""ETL_Pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16FRmlVOQct9bYlUwEI60AGYF33HHqN31

Extract --> Transform --> Load

# Extract
"""

import pandas as pd

df = pd.read_csv('/content/final_job_dataset_500')

df.shape

df.head()

df.tail()

df.columns

df.dtypes

df.info()

df.describe()

"""# Data Validation

# Schema Validation
"""

#Structural Validation
df.shape

# Missing Value Validation
df.isnull().sum()

#Duplicate Validation
print(df.duplicated().sum())

#Categorical Validation
print(df['title'].unique())
print()
print(df['company'].unique())
print()
print(df['location'].unique())
print()
print(df['experience'].unique())
print()
print(df['employment_type'].unique())
print()
print(df['industry'].unique())
print()
print(df['work_mode'].unique())

"""# Transform

The primary goal would be to convert the data types of the features, and making the columns ready to load into database.
"""

df.dtypes

#job_id
df['job_id'] = df['job_id'].astype('int64')
print(df['job_id'].dtypes)

#experience
import re
df['experience'] = df['experience'].str.extract(r'(-?\d*\.?\d+)')
df['experience'] = df['experience'].astype('float64')
print(df['experience'].dtypes)

df['experience'].head()

#salary
df['salary'] = df['salary'].str.extract(r'(-?\d*\.?\d+)')
df['salary'] = df['salary'].astype('float64')
print(df['salary'].dtypes)

df['salary'].head()

#date
df['posted_date'] = pd.to_datetime(df['posted_date'],format="%d-%b-%y")
print(df['posted_date'].dtypes)

df['posted_date'].head()

obj_col = df.select_dtypes(include="object").columns
for columns in obj_col:
  df[columns] = df[columns].str.strip()

df.head()

print(type(df['industry'][0]))

df.tail()

df.dtypes

"""# Business Validation"""

#title constraints
val_title = {"ML Engineer", "Data Scientist", "AI Engineer", "Data Analyst", "Data Engineer", "Backend Developer", "Full Stack Developer", "Java Developer", "Software Engineer", "Cloud Engineer"
}
inv_title = df[~df['title'].isin(val_title)]
print("Valid" if len(inv_title)==0 else "Invalid")

#company constraints
val_company = {"Google", "Microsoft", "Amazon", "Adobe", "Meta", "Netflix", "Flipkart", "Infosys", "TCS", "Accenture", "Deloitte", "Cognizant"
}
inv_company = df[~df['company'].isin(val_company)]
print("Valid" if len(inv_company)==0 else "Invalid")

#location constraints
val_location = {"Delhi", "Gurugram", "Noida", "Bangalore", "Pune", "Mumbai", "Kolkata", "Chennai", "Hyderabad"
}
inv_location = df[~df['location'].isin(val_location)]
print(val_location)
print("Valid" if len(inv_location)==0 else "Invalid")

#experience constraints
val_int_exp = {0, 0.5}
inv_int_exp = df[(df['employment_type']=="Internship") & (~df['experience'].isin(val_int_exp))]
print("Valid" if len(inv_int_exp)==0 else "Invalid")

val_full_exp = {0,0.5,1,2}
inv_full_exp = df[(df['employment_type']=="Full-Time") & (~df['experience'].isin(val_full_exp))]
print("Valid" if len(inv_full_exp)==0 else "Invalid")

#salary
salary_ranges = {

    "Data Scientist": {
        "Internship": (4, 6),
        "Full-Time": (8, 15)
    },

    "ML Engineer": {
        "Internship": (4, 7),
        "Full-Time": (10, 18)
    },

    "AI Engineer": {
        "Internship": (5, 8),
        "Full-Time": (12, 20)
    },

    "Data Engineer": {
        "Internship": (3, 6),
        "Full-Time": (8, 16)
    },

    "Data Analyst": {
        "Internship": (2, 4),
        "Full-Time": (4, 10)
    },

    "Software Engineer": {
        "Internship": (3, 6),
        "Full-Time": (6, 15)
    },

    "Java Developer": {
        "Internship": (3, 5),
        "Full-Time": (5, 12)
    },

    "Backend Developer": {
        "Internship": (3, 6),
        "Full-Time": (6, 15)
    },

    "Full Stack Developer": {
        "Internship": (3, 6),
        "Full-Time": (6, 14)
    },

    "Cloud Engineer": {
        "Internship": (4, 7),
        "Full-Time": (8, 18)
    }
}

def is_valid_salary(row):
  job = row['title']
  employment = row['employment_type']
  salary = row['salary']
  min_salary, max_salary = salary_ranges[job][employment]
  return min_salary <= salary <= max_salary

df['val_salary'] = df.apply(is_valid_salary, axis=1)
inv_salary = df[~df['val_salary']]

print("Valid" if len(inv_salary)==0 else "Invalid")

#employment_type
val_employment_type = {"Internship", "Full-Time"}
inv_employment_type = df[~df['employment_type'].isin(val_employment_type)]
print("Valid" if len(inv_employment_type)==0 else "Invalid")

#industry mapping
val_companyToIndustry = {

    "Google": "Technology",
    "Microsoft": "Technology",
    "Meta": "Technology",
    "Adobe": "Technology",
    "Amazon": "E-Commerce",
    "Flipkart": "E-Commerce",
    "Netflix": "Entertainment",
    "Infosys": "IT Services",
    "TCS": "IT Services",
    "Cognizant": "IT Services",
    "Accenture": "Consulting",
    "Deloitte": "Consulting"
}

def is_valid_industry(row):
  company = row['company']
  industry = row['industry']
  return industry == val_companyToIndustry[company]

df['val_industry'] = df.apply(is_valid_industry, axis = 1)
inv_industry = df[~df['val_industry']]
print(inv_industry)

print("Valid" if len(inv_industry)==0 else "Invalid")

#fixing
df["industry"] = df["company"].map(val_companyToIndustry)

df['val_industry'] = df.apply(is_valid_industry, axis = 1)
inv_industry = df[~df['val_industry']]
print(inv_industry)

print("Valid" if len(inv_industry)==0 else "Invalid")

#work mode
val_work_mode = {"Remote", "On-site"}
inv_work_mode = df[~df['work_mode'].isin(val_work_mode)]

print("Valid" if len(inv_work_mode)==0 else "Invalid")

print(df['posted_date'].dtype)

#posted_date
start_date = pd.Timestamp("2026-06-01")
end_date = pd.Timestamp("2026-06-30")

inv_dates = df[(df['posted_date']<start_date) | (df['posted_date']>end_date)]

print("Valid" if len(inv_dates)==0 else "Invalid")

"""# Load"""

df.columns

df.drop(columns=['val_industry', 'val_salary'], inplace=True)

df.columns

df.shape

final_processed_job_dataset = df.to_csv('final_processed_job_dataset', index=False)